local c = ofCanvas(this);
local args = c:getArgs();
local radius, res, drawmode, strokeweight, primode, debug, normalsize = args[1], args[2], args[3], args[4], args[5], 0, 1;
local position, orientation, scale, lookat = ofVec3f(), ofVec3f(), ofVec3f(1, 1, 1), ofVec3f();
;
function M.new();
ofWindow.addListener("setup", this);
if args[1] == nil then radius = 100 end;
if args[2] == nil then res = 1 end;
if args[3] == nil then drawmode = "fill" end;
if args[4] == nil then strokeweight = 1 end;
M.setup();
end;
;
function M.free();
ofWindow.removeListener("setup", this) end;
;
function M.setup();
M.icosphere = ofIcoSpherePrimitive();
M.icosphere:set(radius, math.min(math.abs(res), 6));
M.icosphere:setPosition(position:vec3()) M.icosphere:setOrientation(orientation:vec3()) M.icosphere:setScale(scale:vec3()) end;
;
function M.list(l) M.radius(l[1]) M.res(math.min(math.abs(l[2]), 6)) M.primode(l[3]) M.draw(l[4]) M.stroke(l[5])end;
function M.radius(f) radius=f M.icosphere:setRadius(f) end;
function M.res(f) res=f M.icosphere:setResolution(math.min(math.abs(f), 6)) end;
function M.primode(f) primode=f M.icosphere:setMode(f) end;
function M.draw(s) drawmode=s end;
function M.normalsize(float) normalsize=float end;
function M.stroke(f) strokeweight=f end;
function M.debug(f) debug = f end;
function M.position(l) position.x=l[1] position.y=l[2] position.z=l[3] M.icosphere:setPosition(position:vec3()) end;
function M.orientation(l) orientation.x=l[1] orientation.y=l[2] orientation.z=l[3] M.icosphere:setOrientation(orientation:vec3()) end;
function M.scale(l) scale.x=l[1] scale.y=l[2] scale.z=l[3] M.icosphere:setScale(scale:vec3()) end;
function M.lookat(l) lookat.x=l[1] lookat.y=l[2] lookat.z=l[3] M.icosphere:lookAt(lookat:vec3()) end;
function M.imageID(sym);
if sym == nil then M.imageSource = nil M.lastID = nil return("imageID");
else if sym ~= lastID then;
M.imageSource = require(sym);
M.lastID = sym;
return ofTable("imageID", sym);
end;
end;
end;
;
function M.bang();
ofSetLineWidth(strokeweight);
if M.imageSource ~= nil then M.imageSource.image:getTexture():bind() end;
if drawmode == "fill" then M.icosphere:drawFaces() end;
if drawmode == "point" then M.icosphere:drawVertices() end;
if drawmode == "line" then M.icosphere:drawWireframe() end;
if drawmode == "normal" then M.icosphere:drawNormals(normalsize) end;
if debug > 0 then M.icosphere:drawAxes(debug*100) end;
if M.imageSource ~= nil then M.imageSource.image:getTexture():unbind() end;
return anything;
end;
