local canvas = ofCanvas(this);
local args = canvas:getArgs();
local outlet = ofOutlet(this);
M.image = ofVideoPlayer();
local filename, start, loop = args[1], args[2], args[3];
local loaded = 0;
;
function M.new();
ofWindow.addListener("setup", this);
if args[1] == nil then print("No file loaded") else M.open(filename) end;
if args[2] == 1 then M.play() end;
if args[3] == nil then loop = 0 end end;
;
function M.free();
ofWindow.removeListener("setup", this);
M.image:close() end;
;
function M.setup() M.image:close() M.image:load(filename) end;
;
function M.open(string) ofSetDataPathRoot(ofCanvas(this, 1):getDir()) filename = string;
if ofWindow.exists then;
M.image:close();
M.image:load(filename);
if (M.image:isLoaded()) then;
print("loaded " .. filename);
M.image:update() end end;
end;
function M.update() M.image:update() end;
function M.play() M.image:play() end;
function M.stop() M.image:stop() end;
function M.pause() M.image:setPaused(true) end;
function M.speed(float) M.image:setSpeed(float) end;
function M.frame(float) M.image:setFrame(float) end;
function M.position(float) M.image:setPosition(float) end;
function M.volume(float) M.image:setVolume(float) end;
function M.loop(float) loop = float end;
function M.close() M.image:close() end;
function M.get() outlet:outletList(1, ofTable (M.image:isLoaded(), M.image:isPlaying(), ofClamp(M.image:getCurrentFrame(), 0, M.image:getTotalNumFrames()), M.image:getTotalNumFrames(), M.image:getWidth(), M.image:getHeight(), M.image:getDuration())) end;
function M.imageID() end;
;
function M.bang();
if loop == 0 then M.image:setLoopState(OF_LOOP_NONE) end;
if loop == 1 then M.image:setLoopState(OF_LOOP_NORMAL) end;
if loop == 2 then M.image:setLoopState(OF_LOOP_PALINDROME) end;
M.image:update();
outlet:outletBang(0);
end;
