local canvas = ofCanvas(this);
local args = canvas:getArgs();
local outlet = ofOutlet(this);
M.video = ofVideoGrabber();
local id, width, height = args[1], args[2], args[3];
local opened, devices;
;
function M.new();
ofWindow.addListener("setup", this);
if args[1] == nil then id = 0 end;
if args[2] == nil then width = 320 end;
if args[3] == nil then height = 240 end;
M.setup();
end;
;
function M.free();
M.video:close();
ofWindow.removeListener("setup", this);
end;
function M.setup();
if ofWindow.exists then;
M.video:setDeviceID(id);
M.video:setup(width, height);
end;
end;
function M.dimen(list);
M.video:setup(list[1], list[2]);
end;
function M.close();
M.video:close();
end;
;
function M.listdev();
devices = M.video:listDevices();
print(devices);
end;
function M.open(float);
M.video:close();
if ofWindow.exists then;
ofDisableArbTex();
M.video:setDeviceID(math.floor(float));
M.video:setup(width, height);
end;
end;
function M.get() outlet:outletList(1, ofTable (M.video:isInitialized(), M.video:getWidth(), M.video:getHeight(), M.video:getTexturePlanes()));
end;
;
function M.bang();
M.video:update();
M.video:bind();
outlet:outletBang(0);
M.video:unbind();
end;
