local canvas = ofCanvas(this);
local args = canvas:getArgs();
local outlet = ofOutlet(this);
M.image = ofVideoGrabber();
local id, width, height = args[1], args[2], args[3];
local opened, devices;
;
function M.new();
ofWindow.addListener("setup", this);
if args[1] == nil then id = 0 end;
if args[2] == nil then width = 320 end;
if args[3] == nil then height = 240 end;
M.setup();
end;
;
function M.free();
M.image:close();
ofWindow.removeListener("setup", this);
end;
function M.setup();
if ofWindow.exists then;
M.image:setDeviceID(id);
M.image:setup(width, height);
end;
end;
function M.dimen(list);
M.image:setup(list[1], list[2]);
end;
function M.close();
M.image:close();
end;
;
function M.listdev();
devices = M.image:listDevices();
print(devices);
end;
function M.open(float);
M.image:close();
if ofWindow.exists then;
ofDisableArbTex();
M.image:setDeviceID(math.floor(float));
M.image:setup(width, height);
end;
end;
function M.get() outlet:outletList(1, ofTable (M.image:isInitialized(), M.image:getWidth(), M.image:getHeight(), M.image:getTexturePlanes()));
end;
;
function M.bang();
M.image:update();
outlet:outletBang(0);
end;
